language: python
python:
  - "3.9"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
services:
  - docker
script:
  - pytest #run tests
after_success:
  - codecov # get coverage